networks:
  api-network:
    external: true
    name: "mongo-network"
  mongodb-network:
  redis-network:


services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    environment:
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017
      - REDIS_URI=redis://redis:6379
      - ENABLE_WRITING_HANDLERS=false
    ports:
      - '9000:9000'
    networks:
      - api-network
      - redis-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:8.0-rc
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - api-network
      - mongodb-network
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    container_name: express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongodb-network
    depends_on:
      - mongodb
    profiles:
      - dev

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  mongodb-seed:
    image: mongo:8.0-rc
    container_name: mongodb-seed
    depends_on:
      - mongodb
    networks:
      - mongodb-network
    volumes:
      - ./seeding.json:/seeding.json
    links:
      - mongodb
    command: >
      mongoimport --host mongodb
                  --db tmdb_movies
                  --collection movies
                  --authenticationDatabase admin
                  --username admin
                  --password secret
                  --drop
                  --jsonArray
                  --file /seeding.json
    profiles:
      - dev

volumes:
  mongodb_data:
