services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017
      REDIS_URI: redis://redis:6379
      ENABLE_WRITING_HANDLERS: 'false'
    ports:
      - '9000:9000'
